# functions starts with A

In [1]:
import numpy as np
arr=np.array([1,2,4,-2,3,-5])
arr

array([ 1,  2,  4, -2,  3, -5])

In [2]:
# 1.absolute
abs(arr)

array([1, 2, 4, 2, 3, 5])

In [3]:
np.absolute(arr)

array([1, 2, 4, 2, 3, 5])

In [4]:
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# 3.accumulate will add the numbers and put values like 1,2+1,3+2+1,....,10+9+8+7+6+5+4+3+2+1
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [6]:
# 4.add function
a=np.array([1,2,3,4,5])
b=np.array([5,4,3,2,1])
np.add(a,b)

array([6, 6, 6, 6, 6])

In [7]:
# for checking the zeros valuesa
all(a)

True

In [8]:
any(a)

True

In [9]:
np.alltrue(a)

True

In [10]:
a.all()

True

In [11]:
a.any()

True

In [12]:
# angle gives you the angle in radian and degree
np.angle(1+1j) # angle in radian

0.7853981633974483

In [13]:
np.angle(1+1j,deg=True) # angle in degree

45.0

In [14]:
# append will add elements 
print(a)
np.append(a,[15,18,19,20],axis=0)

[1 2 3 4 5]


array([ 1,  2,  3,  4,  5, 15, 18, 19, 20])

In [15]:
# arange will give you the list of numbers
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arcsin(0.123)

0.12331227519187199

In [17]:
np.arccos(0.123)

1.4474840516030247

In [18]:
np.arctan(1)

0.7853981633974483

In [19]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# argument max,min, arg give you the index of that minimum and maximum number
np.argmax(x)

9

In [21]:
np.argmin(x)

0

In [22]:
# argsort gives you in which indexes you do so the whole array will be sorted
np.argsort(b)

array([4, 3, 2, 1, 0])

In [23]:
np.average(a)
# gives the average

3.0

# functions starts with B

In [24]:
# this will count how many time the numbers are there
np.bincount(a)

array([0, 1, 1, 1, 1, 1])

In [25]:
bins=np.random.randint(10,20,50)
bins

array([17, 12, 18, 10, 16, 14, 13, 16, 16, 12, 13, 13, 12, 13, 12, 16, 10,
       17, 11, 16, 13, 15, 15, 19, 12, 10, 19, 19, 18, 18, 10, 12, 15, 19,
       16, 18, 18, 17, 18, 12, 13, 13, 19, 16, 14, 19, 19, 19, 12, 11])

In [26]:
np.bincount(bins)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 2, 8, 7, 2, 3, 7, 3, 6, 8])

In [27]:
np.bincount(bins)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 2, 8, 7, 2, 3, 7, 3, 6, 8])

# Functions with C

In [28]:
ceil=np.array([1.7,2.4,-1.3,4,5.9,1.1])

In [29]:
ceil

array([ 1.7,  2.4, -1.3,  4. ,  5.9,  1.1])

In [30]:
np.ceil(ceil) # will give you the value more then the point

array([ 2.,  3., -1.,  4.,  6.,  2.])

In [31]:
# use of floor
np.floor(ceil)

array([ 1.,  2., -2.,  4.,  5.,  1.])

In [32]:
# round
np.round(ceil)

array([ 2.,  2., -1.,  4.,  6.,  1.])

In [33]:
np.fix(ceil)

array([ 1.,  2., -1.,  4.,  5.,  1.])

In [34]:
# use of clip will not accept more than 4 and if more than 4 is there then it will return 4 and minimum it return 1
print(a)
np.clip(a=a,a_min=1,a_max=4) 

[1 2 3 4 5]


array([1, 2, 3, 4, 4])

In [35]:
print(a)
np.column_stack(a)

[1 2 3 4 5]


array([[1, 2, 3, 4, 5]])

In [36]:
# concatenation
np.concatenate((a,a))

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [37]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 5, 4, 3, 2, 1])

In [38]:
# cumsum() gives you the sum
print(a)
np.cumsum(a)

[1 2 3 4 5]


array([ 1,  3,  6, 10, 15])

In [39]:
np.cumprod(a)

array([  1,   2,   6,  24, 120])

In [40]:
np.prod(a)

120

In [41]:
np.sum(a)

15

# Functions with D,E,F

In [42]:
# it will simple delete that array
del a

In [43]:
# a

In [44]:
m=np.matrix('1 2 3;56 78 89;23 34 53')
m

matrix([[ 1,  2,  3],
        [56, 78, 89],
        [23, 34, 53]])

In [45]:
# deteminant of array
np.linalg.det(m)

-404.00000000000017

In [46]:
# diagonals 
np.diag(m)

array([ 1, 78, 53])

In [47]:
np.diagonal(m)

array([ 1, 78, 53])

In [48]:
np.diagflat(m)

matrix([[ 1,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  2,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  3,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0, 56,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, 78,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0, 89,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0, 23,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0, 34,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0, 53]])

In [49]:
# difference
print(m)
np.diff(m)

[[ 1  2  3]
 [56 78 89]
 [23 34 53]]


matrix([[ 1,  1],
        [22, 11],
        [11, 19]])

In [50]:
print(arr)
np.diff(arr)

[ 1  2  4 -2  3 -5]


array([ 1,  2, -6,  5, -8])

In [51]:
np.empty(10)

array([ 6.90468233e-310,  4.67861825e-310,  6.90468182e-310,
        4.67861801e-310, -1.24053623e+120,  6.90468104e-310,
        4.67861800e-310,  6.17478498e-029,  6.90468184e-310,
        4.67861800e-310])

In [52]:
np.empty((10),int)

array([    139752326143296,      94696287617792,     139752315882160,
            94696282659024, 6403765751080147779,     139752300000272,
            94696282646464, 4184848546461803280,     139752316284720,
            94696282527696])

In [53]:
# ones
print(np.ones(5))
print()
print(np.zeros(5))
print()
print(np.eye(5))


[1. 1. 1. 1. 1.]

[0. 0. 0. 0. 0.]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [54]:
# empty_like will empty the array
print(arr)
print(np.empty_like(arr))

[ 1  2  4 -2  3 -5]
[ 4607182418800017408  4611686018427387904 -4616189618054758400
  4616189618054758400  4617315517961601024  4607182418800017408]


In [55]:
# same as ones_like and zeros like
print(np.ones_like(arr))
print(np.zeros_like(arr))

[1 1 1 1 1 1]
[0 0 0 0 0 0]


In [56]:
# fill with any element change every elemnt with that element
arr.fill(8)
arr

array([8, 8, 8, 8, 8, 8])

In [57]:
# flatten and ravel used to simply flat the array
print(m)
print(m.flatten())
print(np.ravel(m))

[[ 1  2  3]
 [56 78 89]
 [23 34 53]]
[[ 1  2  3 56 78 89 23 34 53]]
[ 1  2  3 56 78 89 23 34 53]


In [58]:
# you wanna find the hypoteneous of the triangle then use hypot
np.hypot(3,4)

5.0

In [59]:
np.hypot(6,8)

10.0

In [60]:
# identity 
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [61]:
# indices
np.indices((2,3))

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

In [62]:
a=np.array([1,2,3,4,5])


In [63]:
# inner
np.inner(a,b)

35

In [64]:
np.outer(a,b)

array([[ 5,  4,  3,  2,  1],
       [10,  8,  6,  4,  2],
       [15, 12,  9,  6,  3],
       [20, 16, 12,  8,  4],
       [25, 20, 15, 10,  5]])

In [65]:
np.outer(b,a)

array([[ 5, 10, 15, 20, 25],
       [ 4,  8, 12, 16, 20],
       [ 3,  6,  9, 12, 15],
       [ 2,  4,  6,  8, 10],
       [ 1,  2,  3,  4,  5]])

In [66]:
np.inner(b,a)
# sum of above diagonals

35

In [67]:
# insert
np.insert(a,[1,5],50)

array([ 1, 50,  2,  3,  4,  5, 50])

In [68]:
a

array([1, 2, 3, 4, 5])

In [69]:
np.iscomplex(a)

array([False, False, False, False, False])

In [70]:
np.iscomplexobj(a)

False

In [71]:
# linspace means evenly spaced variables
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [72]:
np.linspace(0,100,15,endpoint=False) # endpoint will remove the endpoint

array([ 0.        ,  6.66666667, 13.33333333, 20.        , 26.66666667,
       33.33333333, 40.        , 46.66666667, 53.33333333, 60.        ,
       66.66666667, 73.33333333, 80.        , 86.66666667, 93.33333333])

In [73]:
np.linspace(0,100,15,endpoint=False,retstep=True) # retstep gives you the second element or first index element

(array([ 0.        ,  6.66666667, 13.33333333, 20.        , 26.66666667,
        33.33333333, 40.        , 46.66666667, 53.33333333, 60.        ,
        66.66666667, 73.33333333, 80.        , 86.66666667, 93.33333333]),
 6.666666666666667)

In [74]:
np.logspace(0,5,6)

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [75]:
# matrix 
a

array([1, 2, 3, 4, 5])

In [76]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [77]:
np.matrix(a)

matrix([[1, 2, 3, 4, 5]])

In [78]:
np.max(a)

5

In [79]:
np.maximum(a,b) # compare each element with another array elemetn

array([5, 4, 3, 4, 5])

In [80]:
np.min(a)

1

In [81]:
np.minimum(a,b)

array([1, 2, 3, 2, 1])

In [82]:
# dimesnion
np.ndim(a)

1

In [83]:
np.ndim(m)

2

In [84]:
np.ndindex(4)

In [85]:
np.ndindex(5)

In [86]:
np.ptp(a)

4

In [87]:
np.ptp(b)

4

In [88]:
np.ptp(m)

88

In [89]:
# put will change the values 
a.put([0,1,2],[6,7,8])
a

array([6, 7, 8, 4, 5])

In [90]:
np.random.rand(4)

array([0.07791958, 0.73975926, 0.46057798, 0.11079485])

In [91]:
np.random.randn(4)

array([ 0.20965842, -0.80631367,  0.0149121 ,  0.24672978])

In [92]:
np.random.randint(4)

2

In [93]:
np.add.reduce(a)

30

In [94]:
np.multiply.reduce(a)

6720

In [95]:
# repeat will repeat the values
np.repeat(7,4) # repeat 7 four times

array([7, 7, 7, 7])

In [96]:
np.repeat(10,100).reshape(10,10)

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [97]:
np.resize(m,(1,3,1,3))

array([[[[ 1,  2,  3]],

        [[56, 78, 89]],

        [[23, 34, 53]]]])

In [98]:
# if you wanna rotate matrix you can by rot90
print(m)
print()
print()
np.rot90(m)

[[ 1  2  3]
 [56 78 89]
 [23 34 53]]




matrix([[ 3, 89, 53],
        [ 2, 78, 34],
        [ 1, 56, 23]])

In [99]:
a

array([6, 7, 8, 4, 5])

In [100]:
# seed wil fix the values
np.random.seed(3)
np.random.randint(4,10,10)

array([6, 4, 5, 7, 4, 4, 4, 9, 9, 7])

In [101]:
np.tile(a,2)

array([6, 7, 8, 4, 5, 6, 7, 8, 4, 5])

In [102]:
# swapaxes is also there to swap the axis

In [103]:
np.tri(3,4,k=0)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.]])

In [104]:
np.tri(3,4,k=1)

array([[1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [105]:
np.tri(3,4,k=2)

array([[1., 1., 1., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [106]:
np.tri(3,4,k=1)

array([[1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [107]:
# trim zeros
np.trim_zeros(a)

array([6, 7, 8, 4, 5])

In [108]:
a=np.array([0,0,0,0,1,2,3,4,5,0,2,40,56,0,0,0,0])
print(a)

[ 0  0  0  0  1  2  3  4  5  0  2 40 56  0  0  0  0]


In [109]:
np.trim_zeros(a)

array([ 1,  2,  3,  4,  5,  0,  2, 40, 56])

In [110]:
np.trim_zeros(a,'f') # f means trim zeros from front

array([ 1,  2,  3,  4,  5,  0,  2, 40, 56,  0,  0,  0,  0])

In [111]:
np.trim_zeros(a,'b') # b means trim zeros from back

array([ 0,  0,  0,  0,  1,  2,  3,  4,  5,  0,  2, 40, 56])

In [112]:
np.trim_zeros(a,'bf') # bf means back and front

array([ 1,  2,  3,  4,  5,  0,  2, 40, 56])

In [113]:
# transpose of a matrix
a.T

array([ 0,  0,  0,  0,  1,  2,  3,  4,  5,  0,  2, 40, 56,  0,  0,  0,  0])

In [114]:
print(m)
m.T

[[ 1  2  3]
 [56 78 89]
 [23 34 53]]


matrix([[ 1, 56, 23],
        [ 2, 78, 34],
        [ 3, 89, 53]])

In [115]:
np.transpose(m)

matrix([[ 1, 56, 23],
        [ 2, 78, 34],
        [ 3, 89, 53]])

In [116]:
# take will take out the values from the arrat
a.take([0,0,8,2,3,5,2]) 

array([0, 0, 5, 0, 0, 2, 0])

In [117]:
# variance of a
np.var(a)

237.87543252595157

In [118]:
# standard variance of a
np.std(a)

15.423210837110137

In [119]:
np.mean(a)

6.647058823529412

In [120]:
np.median(a)

0.0

In [121]:
# view will show you the array
a.view()

array([ 0,  0,  0,  0,  1,  2,  3,  4,  5,  0,  2, 40, 56,  0,  0,  0,  0])

In [122]:
# unique will give the unique values and remove the repeated values
np.unique(a)

array([ 0,  1,  2,  3,  4,  5, 40, 56])

In [123]:
np.trunc(ceil)

array([ 1.,  2., -1.,  4.,  5.,  1.])

In [124]:
np.trunc([3.2]) # truncate remove the point value

array([3.])

In [125]:
np.trunc([3.9])

array([3.])