In [2]:
# numpy is used for making arrys
import numpy as np
# check version of numpy 
np.__version__

'1.21.5'

In [5]:
np # np. press tab

<module 'numpy' from '/usr/lib/python3/dist-packages/numpy/__init__.py'>

In [6]:
# this gives you the information about numpy
np?

# UNDERSTANGING DATATYPES IN NUMPY

In [8]:
# list
l=[True,'2',3,4.5]
for i in l:
    print(type(i),end=",")
[type(i) for i in l]

<class 'bool'>,<class 'str'>,<class 'int'>,<class 'float'>,

[bool, str, int, float]

In [10]:
# Fixed type arrays in python
arr=np.array(list(range(10)))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
import array
l=list(range(10))
a=array.array('i',l) # i means integer
a

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# creating arrays from python lists


In [14]:
np.array([1,3,4,5,7])

array([1, 3, 4, 5, 7])

In [16]:
np.array(['2',4.5,9,True,False])

array(['2', '4.5', '9', 'True', 'False'], dtype='<U32')

In [20]:
# zero d array
d1=np.array(10)
d1.ndim

0

In [21]:
d2=np.array(np.arange(10))
d2.ndim

1

In [22]:
d2=np.array(np.arange(1,10)).reshape(3,3)
d2.ndim

2

In [23]:
d2=np.array(np.arange(1,10)).reshape(1,3,3)
d2.ndim

3

# creating arrays from scratch

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.ones((3,5),dtype=bool)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [29]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [30]:
# create an array filled with a linear sequence 
# starting at 0,ending at 20 and seteps by 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
# linspace is used for evenly spaced in between the numbers
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
# 3x3 uniformly distributed array
np.random.random((3,3))

array([[0.01011866, 0.45425828, 0.34222394],
       [0.71977689, 0.85790787, 0.26613017],
       [0.73247444, 0.20833136, 0.08894927]])

In [33]:
np.random.normal(0,1,(3,3))

array([[ 0.17089022, -1.7418477 ,  2.35462158],
       [ 0.16151916,  0.18781938,  0.79531332],
       [ 1.55749488,  0.07994486,  0.63845568]])

In [38]:
np.random.random((3,3))

array([[0.69591356, 0.80666935, 0.6420933 ],
       [0.21500705, 0.25161666, 0.23027657],
       [0.66977748, 0.52132565, 0.98008904]])

In [39]:
np.random.randint(0,10,(3,3))

array([[9, 5, 1],
       [7, 0, 7],
       [9, 4, 0]])

In [40]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
# create empty array from 0-1
np.empty(4)

array([0.25, 0.5 , 0.75, 1.  ])

In [43]:
np.zeros(10,dtype='int16')
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [ ]:
# Data types
bool_
int_
int8
int16
int32
int64
uint8
uint16
uint32
uint64
float_
float16
float32
float64
comples_
np.complex64
np.complex128