# Numpy array Attributes

In [1]:
import numpy as np

In [6]:
np.random.seed(0) # seed for reproducibility
# the seed will not gives you random values again and again 

x=np.random.randint(10,size=6) # 1-d
y=np.random.randint(10,size=(3,4)) # 2-d
z=np.random.randint(10,size=(3,4,5))
print(x,'\n\n',y,'\n\n',z)

[5 0 3 3 7 9] 

 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [9]:
# find the dimesion of the array
x.ndim 

1

In [10]:
y.ndim

2

In [11]:
z.ndim

3

In [12]:
# find the shape of the array
x.shape

(6,)

In [13]:
y.shape

(3, 4)

In [14]:
z.shape

(3, 4, 5)

In [18]:
# size will give you the size of the array
# or simple size will give you that how many elements you are having
x.size

6

In [19]:
y.size

12

In [20]:
z.size

60

In [21]:
# for finding the dtype of the array you can use dtype
x.dtype

dtype('int64')

In [22]:
y.dtype

dtype('int64')

In [23]:
z.dtype

dtype('int64')

In [25]:
np.array([1.0,2.0]).dtype

dtype('float64')

In [26]:
# so there are bytes and itemsize also
x.itemsize

8

In [28]:
# 48 is there becuase int64 contains 8 itemsize so 
# 8 itemsize * number of elements ==> nbytes
# 8x6=>48
x.nbytes


48

In [29]:
y.itemsize

8

In [32]:
y.size

12

In [33]:
y.nbytes

96

In [34]:
x1=np.array(['a','b','c','d'])
y1=np.array([True,False,True,True])
z1=np.array([1.0,3.4,5.0,78.8,9.8])

In [35]:
x1.itemsize
# y1.itemsize
# z1.itemsize

4

In [36]:
x1.size
# y1.size
# z1.size

4

In [37]:
x1.nbytes
# y1.nbytes
# z1.nbytes

16

In [39]:
x1.dtype
# y1.dtype
# z1.dtype

dtype('<U1')

# array indexing : accesing single elements as like python lists

In [40]:
x

array([5, 0, 3, 3, 7, 9])

In [41]:
x[0] # element at 0th index

5

In [42]:
x[4]

7

In [43]:
x[-1]

9

In [44]:
y[-3]

array([3, 5, 2, 4])

In [45]:
y[-3][-1]

4

In [46]:
y[0,0]

3

In [47]:
x[0,0] # because it is one d array

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [50]:
z[1]

array([[0, 1, 9, 9, 0],
       [4, 7, 3, 2, 7],
       [2, 0, 0, 4, 5],
       [5, 6, 8, 4, 1]])

In [51]:
z[1,2]

array([2, 0, 0, 4, 5])

In [52]:
z[1,2,2]

0

In [53]:
z[2,-1,3]

6

# how we can change elemnts using indexing

In [54]:
x

array([5, 0, 3, 3, 7, 9])

In [57]:
x[0]='3'

In [58]:
x

array([3, 0, 3, 3, 7, 9])

In [62]:
x[1]=3.14159
x # this will be truncated 
# because the dtype is int and integer part only will take it

array([3, 3, 3, 3, 7, 3])

In [63]:
x[0]='preet rathee' # error because it only take integer part

ValueError: invalid literal for int() with base 10: 'preet rathee'

# slicing in arrays

In [64]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
x[:5] # upto 5

array([0, 1, 2, 3, 4])

In [66]:
x[::-1] # reverse the array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [68]:
x[-1:-5:-1]

array([9, 8, 7, 6])

This is how we change elements by slicing

In [69]:
x[::2]=4,5,6,8,9

In [70]:
x

array([4, 1, 5, 3, 6, 5, 8, 7, 9, 9])

slicing on multidimensional array

In [81]:
x=np.random.randint(1,12,12).reshape(3,4)
x

array([[ 4,  5,  5,  9],
       [ 5,  4, 11,  8],
       [ 6,  6,  1,  2]])

In [82]:
x[:2,:3] # two rows and three columns

array([[ 4,  5,  5],
       [ 5,  4, 11]])

In [83]:
x[:3,::2]

array([[ 4,  5],
       [ 5, 11],
       [ 6,  1]])

In [84]:
x[::1,::-1]

array([[ 9,  5,  5,  4],
       [ 8, 11,  4,  5],
       [ 2,  1,  6,  6]])

In [87]:
x[:,0] # first column

array([4, 5, 6])

In [88]:
x[0,:]

array([4, 5, 5, 9])

In [89]:
x[1,:]

array([ 5,  4, 11,  8])

In [90]:
x[2,:]

array([6, 6, 1, 2])

# creating copies of arrays

In [91]:
xcopy=x[:2,:2].copy()
xcopy

array([[4, 5],
       [5, 4]])

In [92]:
xcopy[0,0]=54

In [93]:
xcopy

array([[54,  5],
       [ 5,  4]])

# Reshaping of the arrays

In [94]:
# reshape is used for reshaping the array 
# the value of rowXcolumns => reshpae value
x

array([[ 4,  5,  5,  9],
       [ 5,  4, 11,  8],
       [ 6,  6,  1,  2]])

In [95]:
x.reshape(2,2,3)

array([[[ 4,  5,  5],
        [ 9,  5,  4]],

       [[11,  8,  6],
        [ 6,  1,  2]]])

In [97]:
x.reshape(1,2,6)

array([[[ 4,  5,  5,  9,  5,  4],
        [11,  8,  6,  6,  1,  2]]])

In [98]:
x.reshape(12)

array([ 4,  5,  5,  9,  5,  4, 11,  8,  6,  6,  1,  2])

# Array Concatenation and splitting

concatenation of arrays means join two arrays

In [99]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [100]:
z=[99,99,23,43]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 23, 43])

In [101]:
arr=np.array([[1,2,3],[4,5,6]])
np.concatenate([arr,arr])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [104]:
np.concatenate([x,arr]) # error because x is 1-d array and arr is 2-d array 
# so concatenation is done in between the same dimensional arrays

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [105]:
# in concatenation we can use axis for row wise
np.concatenate([arr,arr],axis=1) # axis 0 is default

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [106]:
np.concatenate([arr,arr],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

hstack and vstack is also there because hstack horizontal join and vstack is vertical concatenation

hstack and vstack add two different dimesionals 
but the dimesnion must be same in hstack both must have same dimesnion and vstack have different dimesional but same elements

In [110]:
np.vstack([arr,arr])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [111]:
np.vstack([x,arr]) 

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [116]:
x1=np.array([[34],[78]])
np.hstack([x1,arr])

array([[34,  1,  2,  3],
       [78,  4,  5,  6]])

# Splitting of arrays

In [117]:
x=[1,2,3,99,99,3,2,1]
x1,x2,x3=np.split(x,[3,5]) # 3,5 are indexes
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [118]:
grid=np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [119]:
upper,lower=np.vsplit(grid,[2])
print(upper,'\n\n',lower)

[[0 1 2 3]
 [4 5 6 7]] 

 [[ 8  9 10 11]
 [12 13 14 15]]


In [120]:
left,right=np.hsplit(grid,[2])
print(left)
print()
print()
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


there is dsplit also which will split array along the third axis

In [123]:
np.dsplit()